### ISSUE TITLE
0.1-pre-rc-alpha epic

### ISSUE THREAD

**Issue by mixonic** [mixonic/ember-cli-deprecation-workflow#1]
* [x] README updates
* [x] publish on npm
* [ ] make the flush command download a file
* [x] if running with a config, throw if there is not explicit handling of that deprecation
* [x] ensure config/deprecation-workflow.js live reloads (put the config dir into the vendor tree to trigger builds?)
- [x] Format output of `flushDeprecations` to be less crazy.  Make it easier to tweak after saving.
- [x] De-dupe deprecations.  Only add a single entry for each message.

**Comment by rwjblue** [comment]
Confirmed livereload works.

**Comment by rwjblue** [comment]
Added https://github.com/mixonic/ember-cli-deprecation-workflow/issues/15 for the remaining item. Closing...
